[package]
name = "gix"
repository = "https://github.com/Byron/gitoxide"
description = "Interact with git repositories just like git would"
license = "MIT/Apache-2.0"
version = "0.37.2"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "CHANGELOG.md"]
rust-version = "1.64"

[lib]
doctest = false
test = true

[[test]]
name = "git"
path = "tests/git.rs"
required-features = []

[[test]]
name = "git-with-regex"
path = "tests/git-with-regex.rs"
required-features = ["regex"]

[[example]]
name = "clone"
path = "examples/clone.rs"
required-features = ["blocking-network-client"]

[features]

default = ["max-performance-safe"]

#! ### Mutually Exclusive Network Client
#! Either `async-*` or `blocking-*` versions of these toggles may be enabled at a time.

## Make `gix-protocol` available along with an async client.
async-network-client = ["gix-protocol/async-client"]
## Use this if your crate uses `async-std` as runtime, and enable basic runtime integration when connecting to remote servers.
async-network-client-async-std = ["async-std", "async-network-client", "gix-transport/async-std"]
## Make `gix-protocol` available along with a blocking client.
blocking-network-client = ["gix-protocol/blocking-client"]
## Stacks with `blocking-network-client` to provide support for HTTP/S using **curl**, and implies blocking networking as a whole.
blocking-http-transport-curl = ["blocking-network-client", "gix-transport/http-client-curl"]
## Stacks with `blocking-network-client` to provide support for HTTP/S using **reqwest**, and implies blocking networking as a whole.
blocking-http-transport-reqwest = ["blocking-network-client", "gix-transport/http-client-reqwest"]
## Stacks with `blocking-http-transport-reqwest` and enables HTTPS via the `rustls` crate. Note that https isn't available without a selection.
blocking-http-transport-reqwest-rust-tls = ["blocking-http-transport-reqwest", "reqwest-for-configuration-only/rustls-tls", "reqwest-for-configuration-only/trust-dns"]
## Stacks with `blocking-http-transport-reqwest` and enables HTTPS via the `native-tls` crate. Note that https isn't available without a selection.
blocking-http-transport-reqwest-native-tls = ["blocking-http-transport-reqwest", "reqwest-for-configuration-only/default-tls" ]


#! ### Other

## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde1 = [  "serde",
            "gix-pack/serde1",
            "gix-object/serde1",
            "gix-protocol?/serde1",
            "gix-transport?/serde1",
            "gix-ref/serde1",
            "gix-odb/serde1",
            "gix-index/serde1",
            "gix-mailmap/serde1",
            "gix-url/serde1",
            "gix-attributes/serde1",
            "gix-revision/serde1",
            "gix-credentials/serde1" ]

## Activate other features that maximize performance, like usage of threads, `zlib-ng` and access to caching in object databases.
## Note that some platforms might suffer from compile failures, which is when `max-performance-safe` should be used.
max-performance = [ "gix-features/zlib-ng-compat", "fast-sha1", "max-performance-safe" ]

## If enabled, use assembly versions of sha1 on supported platforms.
## This might cause compile failures as well which is why it can be turned off separately.
fast-sha1 = [ "gix-features/fast-sha1" ]

## Activate features that maximize performance, like usage of threads, `zlib-ng` and access to caching in object databases, skipping the ones known to cause compile failures
## on some platforms.
max-performance-safe = [
    "gix-features/parallel",
    "gix-pack/pack-cache-lru-static",
    "gix-pack/pack-cache-lru-dynamic",
    "gix-features/fs-walkdir-parallel"
]
## Print debugging information about usage of object database caches, useful for tuning cache sizes.
cache-efficiency-debug = ["gix-features/cache-efficiency-debug"]



[dependencies]
gix-ref = { version = "^0.24.1", path = "../gix-ref" }
gix-discover = { version = "^0.13.1", path = "../gix-discover" }
gix-tempfile = { version = "^3.0.0", path = "../gix-tempfile" }
gix-lock = { version = "^3.0.0", path = "../gix-lock" }
gix-validate = { version = "^0.7.3", path = "../gix-validate" }
gix-sec = { version = "^0.6.2", path = "../gix-sec" }
gix-date = { version = "^0.4.3", path = "../gix-date" }
gix-refspec = { version = "^0.7.3", path = "../gix-refspec" }

gix-config = { version = "^0.16.3", path = "../gix-config" }
gix-odb = { version = "^0.40.2", path = "../gix-odb" }
gix-hash = { version = "^0.10.3", path = "../gix-hash" }
gix-object = { version = "^0.26.4", path = "../gix-object" }
gix-actor = { version = "^0.17.2", path = "../gix-actor" }
gix-pack = { version = "^0.30.3", path = "../gix-pack", features = ["object-cache-dynamic"] }
gix-revision = { version = "^0.10.4", path = "../gix-revision" }

gix-path = { version = "^0.7.2", path = "../gix-path" }
gix-url = { version = "^0.13.3", path = "../gix-url" }
gix-traverse = { version = "^0.22.2", path = "../gix-traverse" }
gix-protocol = { version = "^0.26.4", path = "../gix-protocol", optional = true }
gix-transport = { version = "^0.25.6", path = "../gix-transport", optional = true }
gix-diff = { version = "^0.26.3", path = "../gix-diff" }
gix-mailmap = { version = "^0.9.3", path = "../gix-mailmap" }
gix-features = { version = "^0.26.5", path = "../gix-features", features = ["progress", "once_cell"] }

gix-attributes = { version = "^0.8.3", path = "../gix-attributes" }
gix-glob = { version = "^0.5.5", path = "../gix-glob" }
gix-credentials = { version = "^0.9.2", path = "../gix-credentials" }
gix-prompt = { version = "^0.3.2", path = "../gix-prompt" }
gix-index = { version = "^0.12.4", path = "../gix-index" }
gix-worktree = { version = "^0.12.3", path = "../gix-worktree" }
gix-hashtable = { version = "^0.1.1", path = "../gix-hashtable" }

prodash = { version = "23.0.0", default-features = false, features = ["progress-tree"] }
once_cell = "1.14.0"
signal-hook = { version = "0.3.9", default-features = false }
thiserror = "1.0.26"
log = "0.4.14"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}
smallvec = "1.9.0"
async-std = { version = "1.12.0", optional = true }

## For use in rev-parse, which provides searching commits by running a regex on their message.
##
## If disabled, the text will be search verbatim in any portion of the commit message, similar to
## how a simple unanchored regex of only 'normal' characters would work.
regex = { version = "1.6.0", optional = true, default-features = false, features = ["std"] }

# For internal use to allow pure-Rust builds without openssl.
reqwest-for-configuration-only = { package = "reqwest", version = "0.11.13", default-features = false, optional = true }

document-features = { version = "0.2.0", optional = true }

[target.'cfg(target_vendor = "apple")'.dependencies]
unicode-normalization = { version = "0.1.19", default-features = false }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
is_ci = "1.1.1"
anyhow = "1"
walkdir = "2.3.2"
serial_test = "1.0.0"
async-std = { version = "1.12.0", features = ["attributes"] }

[package.metadata.docs.rs]
features = ["document-features", "max-performance", "blocking-network-client", "serde1"]
rustdoc-args = ["--cfg", "docsrs"]
