[package]
name = "gix-prompt"
version = "0.3.2"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A crate of the gitoxide project for handling prompts in the terminal"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "README.md", "CHANGELOG.md"]
rust-version = "1.64"

[lib]
doctest = false

[dependencies]
gix-command = { version = "^0.2.3", path = "../gix-command" }
gix-config-value = { version = "^0.10.1", path = "../gix-config-value" }

thiserror = "1.0.32"
parking_lot = "0.12.1"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.26.1", default-features = false, features = ["term"] }

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}
serial_test = "1.0.0"
expectrl = "0.6.0"
