[package]
name = "gix-attributes"
version = "0.8.3"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dealing .gitattributes files"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "CHANGELOG.md"]
rust-version = "1.64"

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde1 = ["serde", "bstr/serde", "gix-glob/serde1", "compact_str/serde"]

[dependencies]
gix-features = { version = "^0.26.5", path = "../gix-features" }
gix-path = { version = "^0.7.2", path = "../gix-path" }
gix-quote = { version = "^0.4.2", path = "../gix-quote" }
gix-glob = { version = "^0.5.5", path = "../gix-glob" }

bstr = { version = "1.3.0", default-features = false, features = ["std", "unicode"]}
unicode-bom = "1.1.4"
thiserror = "1.0.26"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}
compact_str = "0.6.1"

document-features = { version = "0.2.1", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
features = ["document-features"]
