[package]
name = "gix-pathspec"
version = "0.1.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dealing magical pathspecs"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.64"

[lib]
doctest = false

[dependencies]
gix-glob = { version = "^0.5.5", path = "../gix-glob" }
gix-attributes = { version = "^0.8.3", path = "../gix-attributes" }

bstr = { version = "1.3.0", default-features = false, features = ["std"]}
bitflags = "1.3.2"
thiserror = "1.0.26"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
once_cell = "1.12.0"
